== Notes
todo, move chapter? rename chapter?

=== Branching
Branching in git is a central mechanism to separate development tasks.
abapGit provides the basic git features for handling branches, the feature is delivered to the users, and the users decide how to use the features.
As abapGit runs on the ABAP Application Server and developers use the Application server for development, all development is subject to the how the kernel works.
The ABAP Kernel only allows one version of an object to be active at a time, ie. developers cannot have multiple versions of the same program running at the same time,
this also means typically git branching is not possible within the same ABAP system.

If more active branches are required for development or testing, more application servers are required in the landscape.

=== File Format
abapGit is developer focused, so the files generated by abapGit are developer focused, this means each file
is stored in git in a format that is similar to what is shown in the developer tools.

And as  the code is stored in git, no usernames, timestamps, states (e.g. active/inactive) or other system specific information should be part of the serialized object files.

=== Deployment
abapGit does not focus on deployment of code, however it can be used to deploy code to various systems.

Within a landscape it is recommended to use https://help.sap.com/saphelp_nw73ehp1/helpdata/en/3b/dfba3692dc635ce10000009b38f839/frameset.htm[CTS] for deploying to QA and Production environments.

Compared to abapGit, CTS is

* Reliable - CTS is well tested and has proven very stable over the years
* Auditable - File checksums ensures that the deployment process is auditable, whereas git is designed to be mutable, history can be changed back in time if needed
* Optimized - Good import performance and integrity can be ensured by CTS, where a abapGit import might cause dumps and long runtime

=== Testing
For modern development processes unit testing is important, abapGit does not help with this.
However abapGit can help developers to be introduced to other development workflows, which in turn can raise the awareness and show the importance of automatic testing.

=== Containers
Currently no easy way exists for spawning an ABAP system running in a container.
Hopefully SAP will provide additional tooling and best processes for building ABAP containers.

Once a ABAP container is spawned, https://github.com/jfilak/sapcli[sapcli] or https://github.com/abapGit/REST[REST] https://github.com/marcellourbani/abap-adt-api[based] tooling can be used to deploy the code from git.